
-- V5 package
-- This package provides constants used by v5

-- Package header
local master = diffusion or {}
if master.v5 ~= nil then
    return master.v5
end

local SERVICE_TOPIC = "@"

local MODE_ERROR = 0x00
local MODE_REQUEST = 0x01
local MODE_RESPONSE = 0x02

local SERVICE_PING = 0x01
local SERVICE_FETCH = 0x02
local SERVICE_SUBSCRIBE = 0x03
local SERVICE_UNSUBSCRIBE = 0x04
local SERVICE_CHANGE_PRINCIPAL = 0x05
local SERVICE_SEND = 0x06
local SERVICE_SUBSCRIPTION_CONTROL = 0x0a
local SERVICE_UNSUBSCRIPTION_CONTROL = 0x0b
local SERVICE_STATE_PROVIDER = 0x0c
local SERVICE_QUEUE_EVENT = 0x0d
local SERVICE_CLOSE_CLIENT = 0x0e
local SERVICE_SET_CLIENT_QUEUE_CONFLATION = 0x0f
local SERVICE_THROTTLE_CLIENT_QUEUE = 0x10
local SERVICE_GET_SESSION_DETAILS = 0x11
local SERVICE_CONTROL_REGISTRATION_REQUEST_IMPL = 0x12
local SERVICE_CONTROL_REGISTRATION_PARAMETERS = 0x13
local SERVICE_TOPIC_CONTROL_REGISTRATION = 0x14
local SERVICE_TOPIC_CONTROL_REGISTRATION_PARAMETERS = 0x15
local SERVICE_AUTHENTICATION_CONTROL_REGISTRATION = 0x16
local SERVICE_AUTHENTICATION_CONTROL_REGISTRATION_PARAMETERS = 0x17
local SERVICE_AUTHENTICATION = 0x18
local SERVICE_SESSION_LISTENER_REGISTRATION = 0x19
local SERVICE_SESSION_DETAILS_EVENT = 0x1a
local SERVICE_CLIENT_SEND = 0x1c
local SERVICE_TOPIC_SOURCE_REGISTRATION = 0x1e
local SERVICE_TOPIC_SOURCE_DEREGISTRATION = 0x1f
local SERVICE_TOPIC_SOURCE_STATE = 0x20
local SERVICE_TOPIC_SOURCE_UPDATE = 0x22
local SERVICE_SUBSCRIPTION_NOTIFICATION = 0x28
local SERVICE_GET_TOPIC_DETAILS = 0x29
local SERVICE_UNSUBSCRIPTION_NOTIFICATION = 0x2a
local SERVICE_ADD_TOPIC = 0x2e
local SERVICE_REMOVE_TOPICS = 0x2f
local SERVICE_MISSING_TOPIC = 0x32
local SERVICE_ROUTING_SUBSCRIPTION_CONTROL = 0x33
local SERVICE_ROUTING_SUBSCRIPTION_CONTROLCALLBACK = 0x34

local serviceIdentity = {
    [SERVICE_PING] = "Ping",
    [SERVICE_FETCH] = "Fetch",
    [SERVICE_SUBSCRIBE] = "Subscribe",
    [SERVICE_UNSUBSCRIBE] = "Unsubscribe",
    [SERVICE_CHANGE_PRINCIPAL] = "ChangePrincipal",
    [SERVICE_SEND] = "Send",
    [SERVICE_SUBSCRIPTION_CONTROL] = "Subscription Control",
    [SERVICE_UNSUBSCRIPTION_CONTROL] = "Unsubscription Control",
    [SERVICE_STATE_PROVIDER] = "StateProvider",
    [SERVICE_QUEUE_EVENT] = "QueueEvent",
    [SERVICE_CLOSE_CLIENT] = "CloseClient",
    [SERVICE_SET_CLIENT_QUEUE_CONFLATION] = "SetClientQueueConflation",
    [SERVICE_THROTTLE_CLIENT_QUEUE] = "ThrottleClientQueue",
    [SERVICE_GET_SESSION_DETAILS] = "GetSessionDetails",
    [SERVICE_CONTROL_REGISTRATION_REQUEST_IMPL] = "ControlRegistrationRequestImpl",
    [SERVICE_CONTROL_REGISTRATION_PARAMETERS] = "ControlRegistrationParameters",
    [SERVICE_TOPIC_CONTROL_REGISTRATION] = "TopicControlRegistration",
    [SERVICE_TOPIC_CONTROL_REGISTRATION_PARAMETERS] = "TopicControlRegistrationParameters",
    [SERVICE_AUTHENTICATION_CONTROL_REGISTRATION] = "AuthenticationControlRegistration",
    [SERVICE_AUTHENTICATION_CONTROL_REGISTRATION_PARAMETERS] = "AuthenticationControlRegistrationParameters",
    [SERVICE_AUTHENTICATION] = "Authentication",
    [SERVICE_SESSION_LISTENER_REGISTRATION] = "SessionListenerRegistration",
    [SERVICE_SESSION_DETAILS_EVENT] = "SessionDetailsEvent",
    [SERVICE_CLIENT_SEND] = "ClientSend",
    [SERVICE_TOPIC_SOURCE_REGISTRATION] = "TopicSourceRegistration",
    [SERVICE_TOPIC_SOURCE_DEREGISTRATION] = "TopicSourceDeregistration",
    [SERVICE_TOPIC_SOURCE_STATE] = "TopicSourceState",
    [SERVICE_TOPIC_SOURCE_UPDATE] = "TopicSourceUpdate",
    [SERVICE_SUBSCRIPTION_NOTIFICATION] = "SubscriptionNotification",
    [SERVICE_GET_TOPIC_DETAILS] = "GetTopicDetails",
    [SERVICE_UNSUBSCRIPTION_NOTIFICATION] = "UnsubscriptionNotification",
    [SERVICE_ADD_TOPIC] = "AddTopic",
    [SERVICE_REMOVE_TOPICS] = "RemoveTopics",
    [SERVICE_MISSING_TOPIC] = "MissingTopic",
    [SERVICE_ROUTING_SUBSCRIPTION_CONTROL] = "Routing Subscription Control",
    [SERVICE_ROUTING_SUBSCRIPTION_CONTROLCALLBACK] = "Routing Subscription Control callback"
}

local modeValues = {
    [MODE_ERROR] = "Error",
    [MODE_REQUEST] = "Request",
    [MODE_RESPONSE] = "Response"
}

--- Package footer
master.v5 = {
    SERVICE_PING = SERVICE_PING,
    SERVICE_FETCH = SERVICE_FETCH,
    SERVICE_SUBSCRIBE = SERVICE_SUBSCRIBE,
    SERVICE_UNSUBSCRIBE = SERVICE_UNSUBSCRIBE,
    SERVICE_CHANGE_PRINCIPAL = SERVICE_CHANGE_PRINCIPAL,
    SERVICE_SEND = SERVICE_SEND,
    SERVICE_SUBSCRIPTION_CONTROL = SERVICE_SUBSCRIPTION_CONTROL,
    SERVICE_UNSUBSCRIPTION_CONTROL = SERVICE_UNSUBSCRIPTION_CONTROL,
    SERVICE_STATE_PROVIDER = SERVICE_STATE_PROVIDER,
    SERVICE_QUEUE_EVENT = SERVICE_QUEUE_EVENT,
    SERVICE_CLOSE_CLIENT = SERVICE_CLOSE_CLIENT,
    SERVICE_SET_CLIENT_QUEUE_CONFLATION = SERVICE_SET_CLIENT_QUEUE_CONFLATION,
    SERVICE_THROTTLE_CLIENT_QUEUE = SERVICE_THROTTLE_CLIENT_QUEUE,
    SERVICE_GET_SESSION_DETAILS = SERVICE_GET_SESSION_DETAILS,
    SERVICE_CONTROL_REGISTRATION_REQUEST_IMPL = SERVICE_CONTROL_REGISTRATION_REQUEST_IMPL,
    SERVICE_CONTROL_REGISTRATION_PARAMETERS = SERVICE_CONTROL_REGISTRATION_PARAMETERS,
    SERVICE_TOPIC_CONTROL_REGISTRATION = SERVICE_TOPIC_CONTROL_REGISTRATION,
    SERVICE_TOPIC_CONTROL_REGISTRATION_PARAMETERS = SERVICE_TOPIC_CONTROL_REGISTRATION_PARAMETERS,
    SERVICE_AUTHENTICATION_CONTROL_REGISTRATION = SERVICE_AUTHENTICATION_CONTROL_REGISTRATION,
    SERVICE_AUTHENTICATION_CONTROL_REGISTRATION_PARAMETERS = SERVICE_AUTHENTICATION_CONTROL_REGISTRATION_PARAMETERS,
    SERVICE_AUTHENTICATION = SERVICE_AUTHENTICATION,
    SERVICE_SESSION_LISTENER_REGISTRATION = SERVICE_SESSION_LISTENER_REGISTRATION,
    SERVICE_SESSION_DETAILS_EVENT = SERVICE_SESSION_DETAILS_EVENT,
    SERVICE_CLIENT_SEND = SERVICE_CLIENT_SEND,
    SERVICE_TOPIC_SOURCE_REGISTRATION = SERVICE_TOPIC_SOURCE_REGISTRATION,
    SERVICE_TOPIC_SOURCE_DEREGISTRATION = SERVICE_TOPIC_SOURCE_DEREGISTRATION,
    SERVICE_TOPIC_SOURCE_STATE = SERVICE_TOPIC_SOURCE_STATE,
    SERVICE_TOPIC_SOURCE_UPDATE = SERVICE_TOPIC_SOURCE_UPDATE,
    SERVICE_SUBSCRIPTION_NOTIFICATION = SERVICE_SUBSCRIPTION_NOTIFICATION,
    SERVICE_GET_TOPIC_DETAILS = SERVICE_GET_TOPIC_DETAILS,
    SERVICE_UNSUBSCRIPTION_NOTIFICATION = SERVICE_UNSUBSCRIPTION_NOTIFICATION,
    SERVICE_ADD_TOPIC = SERVICE_ADD_TOPIC,
    SERVICE_REMOVE_TOPICS = SERVICE_REMOVE_TOPICS,
    SERVICE_MISSING_TOPIC = SERVICE_MISSING_TOPIC,
    SERVICE_ROUTING_SUBSCRIPTION_CONTROL = SERVICE_ROUTING_SUBSCRIPTION_CONTROL,
    SERVICE_ROUTING_SUBSCRIPTION_CONTROLCALLBACK = SERVICE_ROUTING_SUBSCRIPTION_CONTROLCALLBACK,
    SERVICE_TOPIC = SERVICE_TOPIC,
    MODE_ERROR = MODE_ERROR,
    MODE_REQUEST = MODE_REQUEST,
    MODE_RESPONSE = MODE_RESPONSE,
    serviceIdentity = serviceIdentity,
    modeValues = modeValues
}
diffusion = master
return master.v5