
-- V5 package
-- This package provides constants used by v5

-- Package header
local master = diffusion or {}
if master.v5 ~= nil then
	return master.v5
end


local SERVICE_TOPIC = "@"

local MODE_ERROR = 0x00
local MODE_REQUEST = 0x01
local MODE_RESPONSE = 0x02

local SERVICE_PING = 0x01
local SERVICE_FETCH = 0x02
local SERVICE_SUBSCRIBE = 0x03
local SERVICE_UNSUBSCRIBE = 0x04
local SERVICE_CHANGE_PRINCIPAL = 0x05
local SERVICE_SEND = 0x06
local SERVICE_SUBSCRIPTION_CONTROL = 0x0a
local SERVICE_UNSUBSCRIPTION_CONTROL = 0x0b
local SERVICE_STATE_PROVIDER = 0x0c
local SERVICE_QUEUE_EVENT = 0x0d
local SERVICE_CLOSE_CLIENT = 0x0e
local SERVICE_CONFLATION = 0x0f
local SERVICE_THROTTLE_CLIENT = 0x10
local SERVICE_SESSION_DETAILS = 0x11
local SERVICE_CONTROL_REGISTRATION = 0x12
local SERVICE_CONTROL_DEREGISTRATION = 0x13
local SERVICE_TOPIC_CONTROL_REGISTRATION = 0x14
local SERVICE_TOPIC_CONTROL_DEREGISTRATION = 0x15
local SERVICE_TOPIC_SOURCE_REGISTRATION = 0x1e
local SERVICE_TOPIC_SOURCE_DEREGISTRATION = 0x1f
local SERVICE_TOPIC_SOURCE_STATE = 0x20
local SERVICE_TOPIC_SOURCE_UPDATE = 0x22
local SERVICE_ADD_TOPIC = 0x2e
local SERVICE_REMOVE_TOPIC = 0x2f

-- Package footer
master.v5 = {
	SERVICE_TOPIC = SERVICE_TOPIC,
	MODE_ERROR = MODE_ERROR,
	MODE_REQUEST = MODE_REQUEST,
	MODE_RESPONSE = MODE_RESPONSE,
	SERVICE_PING = SERVICE_PING,
	SERVICE_FETCH = SERVICE_FETCH,
	SERVICE_SUBSCRIBE = SERVICE_SUBSCRIBE,
	SERVICE_UNSUBSCRIBE = SERVICE_UNSUBSCRIBE,
	SERVICE_CHANGE_PRINCIPAL = SERVICE_CHANGE_PRINCIPAL,
	SERVICE_TOPIC_SOURCE_REGISTRATION = SERVICE_TOPIC_SOURCE_REGISTRATION,
	SERVICE_TOPIC_SOURCE_DEREGISTRATION = SERVICE_TOPIC_SOURCE_DEREGISTRATION,
	SERVICE_TOPIC_SOURCE_STATE = SERVICE_TOPIC_SOURCE_STATE,
	SERVICE_TOPIC_SOURCE_UPDATE = SERVICE_TOPIC_SOURCE_UPDATE,
	SERVICE_ADD_TOPIC = SERVICE_ADD_TOPIC,
	SERVICE_REMOVE_TOPIC = SERVICE_REMOVE_TOPIC
}
diffusion = master
return master.v5